# ==============================================================================
# PROFILING MACROS - Clean, reusable profiling targets
# ==============================================================================
# Usage: include(cmake/Profiling.cmake) in your main CMakeLists.txt
# Then use: add_full_profiling(your_target_name) in any CMakeLists.txt

# Find required tools
set(PERF_EXECUTABLE "/usr/lib/linux-tools/6.8.0-71-generic/perf")
find_program(INFERNO_EXECUTABLE inferno-flamegraph)
find_program(SPEEDSCOPE_EXECUTABLE speedscope)
find_program(ORIGINAL_FLAMEGRAPH_EXECUTABLE flamegraph.pl)

if(EXISTS ${PERF_EXECUTABLE})
    message(STATUS "Profiling tools found: ${PERF_EXECUTABLE}")

    if(INFERNO_EXECUTABLE)
        message(STATUS "Flamegraph tool found: inferno-flamegraph")
    else()
        message(STATUS "Flamegraph tool missing: inferno-flamegraph (install with: cargo install inferno)")
    endif()

    if(SPEEDSCOPE_EXECUTABLE)
        message(STATUS "Interactive profiler found: speedscope")
    else()
        message(STATUS "Interactive profiler missing: speedscope (install with: npm install -g speedscope)")
    endif()

    if(ORIGINAL_FLAMEGRAPH_EXECUTABLE)
        message(STATUS "Original FlameGraph found: flamegraph.pl")
    else()
        message(STATUS "Original FlameGraph missing: flamegraph.pl")
    endif()

    # ==============================================================================
    # PROFILING MACROS - Use these in your CMakeLists.txt files
    # ==============================================================================

    # Macro: add_profiling(target_name)
    # Adds basic perf profiling to any executable target
    macro(add_profiling target_name)
        add_custom_target(profile_${target_name}
            COMMAND echo "🔥 Profiling ${target_name}..."
            COMMAND ${PERF_EXECUTABLE} record -F 4000 -g --call-graph=fp
            -o ${CMAKE_BINARY_DIR}/${target_name}.perf.data
            $<TARGET_FILE:${target_name}>
            DEPENDS ${target_name}
            WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
            COMMENT "Profiling ${target_name} with perf"
        )
    endmacro()

    # Macro: add_flamegraph(target_name)
    # Adds flamegraph generation (requires add_profiling first)
    macro(add_flamegraph target_name)
        if(INFERNO_EXECUTABLE)
            add_custom_target(flamegraph_${target_name}
                COMMAND echo "🔥 Generating flamegraph for ${target_name}..."
                COMMAND ${PERF_EXECUTABLE} script -i ${CMAKE_BINARY_DIR}/${target_name}.perf.data |
                inferno-collapse-perf | ${INFERNO_EXECUTABLE}
                --title "${target_name} Performance Profile"
                --subtitle "Generated by STL C++26 Project"
                --width 1600 --height 20 --colors rust
                > ${CMAKE_BINARY_DIR}/${target_name}_flamegraph.svg
                COMMAND echo "📊 Flamegraph: ${CMAKE_BINARY_DIR}/${target_name}_flamegraph.svg"
                DEPENDS profile_${target_name}
                WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
                COMMENT "Generating flamegraph for ${target_name}"
            )
        endif()
    endmacro()

    # Macro: add_flamechart(target_name)
    # Adds flamechart generation (chronological timeline)
    macro(add_flamechart target_name)
        if(INFERNO_EXECUTABLE)
            add_custom_target(flamechart_${target_name}
                COMMAND echo "📈 Generating flamechart for ${target_name}..."
                COMMAND ${PERF_EXECUTABLE} script -i ${CMAKE_BINARY_DIR}/${target_name}.perf.data |
                inferno-collapse-perf | ${INFERNO_EXECUTABLE} --flamechart
                --title "${target_name} Execution Timeline"
                --subtitle "Flamechart - Shows execution flow over time"
                --width 1600 --height 20 --colors rust
                > ${CMAKE_BINARY_DIR}/${target_name}_flamechart.svg
                COMMAND echo "📈 Flamechart: ${CMAKE_BINARY_DIR}/${target_name}_flamechart.svg"
                DEPENDS profile_${target_name}
                WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
                COMMENT "Generating flamechart for ${target_name}"
            )
        endif()
    endmacro()

    # Macro: add_speedscope(target_name)
    # Adds Speedscope data generation for modern interactive profiling
    macro(add_speedscope target_name)
        if(SPEEDSCOPE_EXECUTABLE)
            add_custom_target(speedscope_${target_name}
                COMMAND echo "🚀 Preparing Speedscope data for ${target_name}..."
                COMMAND ${PERF_EXECUTABLE} script -i ${CMAKE_BINARY_DIR}/${target_name}.perf.data
                > ${CMAKE_BINARY_DIR}/${target_name}.perf.script
                COMMAND echo "🌐 Speedscope file: ${CMAKE_BINARY_DIR}/${target_name}.perf.script"
                COMMAND echo "   Upload at: https://speedscope.app"
                COMMAND echo "   Or run: speedscope ${CMAKE_BINARY_DIR}/${target_name}.perf.script"
                DEPENDS profile_${target_name}
                WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
                COMMENT "Preparing Speedscope data for ${target_name}"
            )
        endif()
    endmacro()

    # Macro: add_full_profiling(target_name)
    # Convenience macro that adds all profiling types
    macro(add_full_profiling target_name)
        add_profiling(${target_name})
        add_flamegraph(${target_name})
        add_flamechart(${target_name})
        add_speedscope(${target_name})

        # Create a combined target for easy access
        set(AVAILABLE_TARGETS profile_${target_name})

        if(INFERNO_EXECUTABLE)
            list(APPEND AVAILABLE_TARGETS flamegraph_${target_name} flamechart_${target_name})
        endif()

        if(SPEEDSCOPE_EXECUTABLE)
            list(APPEND AVAILABLE_TARGETS speedscope_${target_name})
        endif()

        add_custom_target(flame_${target_name}
            DEPENDS ${AVAILABLE_TARGETS}
            COMMENT "Complete profiling suite for ${target_name}"
        )
    endmacro()

    message(STATUS "🔥 Profiling macros available:")
    message(STATUS "  add_profiling(target)      - Basic perf profiling")
    message(STATUS "  add_flamegraph(target)     - Add flamegraph generation")
    message(STATUS "  add_flamechart(target)     - Add flamechart generation")
    message(STATUS "  add_speedscope(target)     - Add Speedscope data prep")
    message(STATUS "  add_full_profiling(target) - Add all profiling types")

else()
    # Create dummy macros when profiling tools are not available
    macro(add_profiling target_name)
        # Silently do nothing when tools are missing
    endmacro()

    macro(add_flamegraph target_name)
        # Silently do nothing when tools are missing
    endmacro()

    macro(add_flamechart target_name)
        # Silently do nothing when tools are missing
    endmacro()

    macro(add_speedscope target_name)
        # Silently do nothing when tools are missing
    endmacro()

    macro(add_full_profiling target_name)
        # Silently do nothing when tools are missing
    endmacro()

    message(WARNING "⚠️  Profiling not available - missing tools")

    if(NOT EXISTS ${PERF_EXECUTABLE})
        message(STATUS "   perf not found at ${PERF_EXECUTABLE}")
    endif()

    if(NOT INFERNO_EXECUTABLE)
        message(STATUS "   inferno-flamegraph not found (cargo install inferno)")
    endif()
endif()
